<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-07-05T23:11:50 IST" name="Default suite" finished-at="2020-07-05T23:12:55 IST" duration-ms="65392">
    <groups>
    </groups>
    <test started-at="2020-07-05T23:11:50 IST" name="Default test" finished-at="2020-07-05T23:12:55 IST" duration-ms="65392">
      <class name="com.training.sanity.tests.RETC038Tests">
        <test-method is-config="true" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.RETC038Tests@47542153]" started-at="2020-07-05T23:11:50 IST" name="setUpBeforeClass" finished-at="2020-07-05T23:11:50 IST" duration-ms="29" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.training.sanity.tests.RETC038Tests@47542153]" started-at="2020-07-05T23:11:50 IST" name="setUp" finished-at="2020-07-05T23:12:07 IST" duration-ms="17016" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validLoginTest()[pri:0, instance:com.training.sanity.tests.RETC038Tests@47542153]" started-at="2020-07-05T23:12:07 IST" name="validLoginTest" finished-at="2020-07-05T23:12:53 IST" duration-ms="46242" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Thanks you for your message] but found [There was an error trying to send your message. Please try again later.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Thanks you for your message] but found [There was an error trying to send your message. Please try again later.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.training.sanity.tests.RETC038Tests.validLoginTest(RETC038Tests.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.training.sanity.tests.RETC038Tests@47542153]" started-at="2020-07-05T23:12:53 IST" name="tearDown" finished-at="2020-07-05T23:12:55 IST" duration-ms="2030" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.RETC038Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
